export const CONFIG = {
  isDemoMode:
    window.location.hostname.includes("github.io") ||
    new URLSearchParams(window.location.search).get("demo") === "true",

  endpoints: {
    portfolio: "/api/portfolio",
    eval: "/api/eval",
    colorStandards: "/api/color-standards",
  },

  demoPaths: {
    primary: "sample_data",
    fallback: "data",
  },

  defaultBucket: "Tactical Opportunities",
  maxTickerLength: 10,
  maxTickerTapeCount: 20,

  animationDelayMs: 30,
  scoreThresholds: { high: 8, low: 4 },
  colorBandFraction: 0.5,

  heatmapWidget: {
    blockSize: "Value.Traded|1W",
    blockColor: "change",
    grouping: "sector",
    locale: "en",
    symbolUrl: "",
    colorTheme: "dark",
    exchanges: ["NYSE", "NASDAQ"],
    hasTopBar: true,
    isDataSetEnabled: false,
    isZoomEnabled: true,
    hasSymbolTooltip: true,
    isMonoSize: false,
    width: "100%",
    height: "100%",
  },
};

export const COLS = {
  all: [
    { key: "ticker", label: "TICKER" },
    { key: "current_price", label: "PRICE", format: "currency" },
    { key: "change_percent", label: "CHANGE%", format: "percent" },
    { key: "market_cap", label: "MKT_CAP", format: "market_cap" },
    { key: "pe", label: "PE", format: "number" },
    { key: "pe_forward", label: "FWD_PE", format: "number" },
    { key: "peg", label: "PEG", format: "number" },
    { key: "beta", label: "BETA", format: "number" },
    { key: "iv", label: "IV", format: "percent_neutral" },
    { key: "one_month_change_percent", label: "1M%", format: "percent" },
    { key: "three_month_change_percent", label: "3M%", format: "percent" },
    { key: "six_month_change_percent", label: "6M%", format: "percent" },
    { key: "one_year_change_percent", label: "1Y%", format: "percent" },
    { key: "median_upside", label: "UPSIDE%", format: "percent" },
    { key: "revenue_growth", label: "GROWTH", format: "percent_neutral" },
    { key: "gross_margin", label: "MARGIN", format: "percent_neutral" },
    { key: "debt_to_equity", label: "DEBT", format: "percent_neutral" },
    { key: "free_cash_flow", label: "FCF", format: "market_cap" },
    { key: "total", label: "VALUE", format: "currency" },
    { key: "weight_pct", label: "WEIGHT", format: "percent_neutral" },
    { key: "rsi", label: "RSI", format: "number" },
    { key: "bucket", label: "STRATEGY" },
    { key: "rank", label: "RANK" },
    { key: "overall", label: "SCORE", format: "score" },
    { key: "quality", label: "QUALITY", format: "score" },
    { key: "valuation", label: "VALUE", format: "score" },
    { key: "moat", label: "MOAT", format: "score" },
    { key: "upside", label: "UPSIDE", format: "score" },
    { key: "bull", label: "BULL", format: "prob" },
    { key: "bear", label: "BEAR", format: "prob" },
    { key: "quantity", label: "QTY", format: "number" },
    { key: "remove", label: "", format: "action" },
  ],
  holdings: [
    { key: "ticker", label: "TICKER" },
    { key: "current_price", label: "PRICE", format: "currency" },
    { key: "change_percent", label: "CHANGE%", format: "percent" },
    { key: "market_cap", label: "MKT_CAP", format: "market_cap" },
    { key: "pe", label: "PE", format: "number" },
    { key: "pe_forward", label: "FWD_PE", format: "number" },
    { key: "peg", label: "PEG", format: "number" },
    { key: "beta", label: "BETA", format: "number" },
    { key: "iv", label: "IV", format: "percent_neutral" },
    { key: "one_month_change_percent", label: "1M%", format: "percent" },
    { key: "three_month_change_percent", label: "3M%", format: "percent" },
    { key: "six_month_change_percent", label: "6M%", format: "percent" },
    { key: "one_year_change_percent", label: "1Y%", format: "percent" },
    { key: "median_upside", label: "UPSIDE%", format: "percent" },
    { key: "revenue_growth", label: "GROWTH", format: "percent" },
    { key: "gross_margin", label: "MARGIN", format: "percent_neutral" },
    { key: "debt_to_equity", label: "DEBT", format: "percent_neutral" },
    { key: "free_cash_flow", label: "FCF", format: "market_cap" },
    { key: "total", label: "VALUE", format: "currency" },
    { key: "weight_pct", label: "WEIGHT", format: "percent_neutral" },
    { key: "rsi", label: "RSI", format: "number" },
    { key: "bucket", label: "STRATEGY" },
    { key: "quantity", label: "QTY", format: "number" },
    { key: "remove", label: "", format: "action" },
  ],
  evaluations: [
    { key: "ticker", label: "TICKER" },
    { key: "rank", label: "RANK" },
    { key: "overall", label: "SCORE", format: "score" },
    { key: "quality", label: "QUALITY", format: "score" },
    { key: "valuation", label: "VALUE", format: "score" },
    { key: "moat", label: "MOAT", format: "score" },
    { key: "upside", label: "UPSIDE", format: "score" },
    { key: "bull", label: "BULL", format: "prob" },
    { key: "bear", label: "BEAR", format: "prob" },
    { key: "remove", label: "", format: "action" },
  ],
};

export const DEFAULT_SORT_COLS = {
  all: "weight_pct",
  holdings: "weight_pct",
  evaluations: "overall",
};
