/** Define shared label enums and label-related models. */

export const SECTOR_LABELS: Record<string, string> = {
	communication_services: "Communication Services",
	consumer_discretionary: "Consumer Discretionary",
	consumer_staples: "Consumer Staples",
	energy: "Energy",
	financials: "Financials",
	health_care: "Health Care",
	industrials: "Industrials",
	materials: "Materials",
	real_estate: "Real Estate",
	technology: "Technology",
	utilities: "Utilities",
	other: "Other",
};

export const SECTOR_PATTERN_RULES: ReadonlyArray<readonly [string, string]> = [
	[String.raw`\bcommunication\b|\btelecom`, "Communication Services"],
	[
		String.raw`\bconsumer\b.*\b(cyclical|discretionary)\b|\bdiscretionary\b`,
		"Consumer Discretionary",
	],
	[
		String.raw`\bconsumer\b.*\b(defensive|staples)\b|\bstaples\b`,
		"Consumer Staples",
	],
	[String.raw`\benergy\b|oil|gas`, "Energy"],
	[
		String.raw`\bfinancial\b|financial services|bank|insurance|capital market|asset management`,
		"Financials",
	],
	[
		String.raw`\bhealth\s*care\b|\bhealthcare\b|biotech|pharma|medical`,
		"Health Care",
	],
	[String.raw`\bindustrial`, "Industrials"],
	[String.raw`\bmaterial\b|basic materials|chemicals|mining`, "Materials"],
	[String.raw`real estate|reit`, "Real Estate"],
	[
		String.raw`\btech\b|technology|software|semiconductor|information technology`,
		"Technology",
	],
	[String.raw`\butilities?\b`, "Utilities"],
];

export const INDUSTRY_LABELS_BY_SECTOR: ReadonlyArray<
	readonly [string, readonly string[]]
> = [
	[
		"Health Care",
		[
			"Biotechnology",
			"Medical Devices",
			"Drug Manufacturers - Specialty & Generic",
			"Medical Instruments & Supplies",
			"Medical Care Facilities",
			"Diagnostics & Research",
			"Health Information Services",
			"Drug Manufacturers - General",
			"Medical Distribution",
			"Healthcare Plans",
			"Pharmaceutical Retailers",
		],
	],
	[
		"Financials",
		[
			"Banks - Regional",
			"Shell Companies",
			"Asset Management",
			"Capital Markets",
			"Credit Services",
			"Insurance - Property & Casualty",
			"Insurance Brokers",
			"Insurance - Life",
			"Banks - Diversified",
			"Insurance - Specialty",
			"Financial Data & Stock Exchanges",
			"Mortgage Finance",
			"Insurance - Diversified",
			"Insurance - Reinsurance",
			"Financial Conglomerates",
		],
	],
	[
		"Technology",
		[
			"Software - Application",
			"Software - Infrastructure",
			"Information Technology Services",
			"Semiconductors",
			"Electronic Components",
			"Communication Equipment",
			"Computer Hardware",
			"Scientific & Technical Instruments",
			"Semiconductor Equipment & Materials",
			"Solar",
			"Consumer Electronics",
			"Electronics & Computer Distribution",
		],
	],
	[
		"Industrials",
		[
			"Aerospace & Defense",
			"Specialty Industrial Machinery",
			"Engineering & Construction",
			"Electrical Equipment & Parts",
			"Specialty Business Services",
			"Marine Shipping",
			"Building Products & Equipment",
			"Integrated Freight & Logistics",
			"Farm & Heavy Construction Machinery",
			"Conglomerates",
			"Consulting Services",
			"Industrial Distribution",
			"Security & Protection Services",
			"Rental & Leasing Services",
			"Waste Management",
			"Airlines",
			"Staffing & Employment Services",
			"Pollution & Treatment Controls",
			"Metal Fabrication",
			"Trucking",
			"Railroads",
			"Tools & Accessories",
			"Airports & Air Services",
			"Business Equipment & Supplies",
			"Infrastructure Operations",
		],
	],
	[
		"Energy",
		[
			"Oil & Gas Exploration & Production",
			"Oil & Gas Midstream",
			"Oil & Gas Equipment & Services",
			"Oil & Gas Refining & Marketing",
			"Oil & Gas Integrated",
			"Uranium",
			"Oil & Gas Drilling",
			"Thermal Coal",
		],
	],
	[
		"Communication Services",
		[
			"Internet Content & Information",
			"Telecom Services",
			"Entertainment",
			"Advertising Agencies",
			"Electronic Gaming & Multimedia",
			"Broadcasting",
			"Publishing",
		],
	],
	[
		"Consumer Staples",
		[
			"Packaged Foods",
			"Education & Training Services",
			"Household & Personal Products",
			"Farm Products",
			"Beverages - Non-Alcoholic",
			"Food Distribution",
			"Grocery Stores",
			"Tobacco",
			"Beverages - Wineries & Distilleries",
			"Discount Stores",
			"Beverages - Brewers",
			"Confectioners",
		],
	],
	[
		"Materials",
		[
			"Specialty Chemicals",
			"Gold",
			"Other Industrial Metals & Mining",
			"Steel",
			"Chemicals",
			"Building Materials",
			"Other Precious Metals & Mining",
			"Agricultural Inputs",
			"Coking Coal",
			"Lumber & Wood Production",
			"Copper",
			"Silver",
			"Paper & Paper Products",
			"Aluminum",
		],
	],
	[
		"Consumer Discretionary",
		[
			"Auto Parts",
			"Restaurants",
			"Specialty Retail",
			"Internet Retail",
			"Furnishings, Fixtures & Appliances",
			"Leisure",
			"Apparel Retail",
			"Auto Manufacturers",
			"Auto & Truck Dealerships",
			"Packaging & Containers",
			"Apparel Manufacturing",
			"Residential Construction",
			"Travel Services",
			"Resorts & Casinos",
			"Recreational Vehicles",
			"Footwear & Accessories",
			"Personal Services",
			"Gambling",
			"Lodging",
			"Luxury Goods",
			"Home Improvement Retail",
			"Textile Manufacturing",
			"Department Stores",
		],
	],
	[
		"Real Estate",
		[
			"Real Estate Services",
			"REIT - Mortgage",
			"REIT - Retail",
			"REIT - Residential",
			"REIT - Office",
			"REIT - Healthcare Facilities",
			"REIT - Specialty",
			"REIT - Industrial",
			"REIT - Diversified",
			"Real Estate - Development",
			"REIT - Hotel & Motel",
			"Real Estate - Diversified",
		],
	],
	[
		"Utilities",
		[
			"Utilities - Regulated Electric",
			"Utilities - Renewable",
			"Utilities - Regulated Gas",
			"Utilities - Regulated Water",
			"Utilities - Independent Power Producers",
			"Utilities - Diversified",
		],
	],
];

export const INDUSTRY_LABELS = INDUSTRY_LABELS_BY_SECTOR.flatMap(
	([, industryLabels]) => [...industryLabels],
);
